--INSERT INTO EMAIL_DETAILS_ED

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('tejaspadhye@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('toaniketdeshmukh@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('hnrick@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('ashutosh.g.joshi@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('rushikeshdeshpande1987@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('toajinkyadeshmukh@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('pranavyogi@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('girishlavekar@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO EMAIL_DETAILS_ED (EMAIL_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('anand30.chaudhary@gmail.com', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--SELECT * FROM SEASONS_DATA_SD

--INSERT INTO MEMBERS_DATA_MD

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Tejas Padhye', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Aniket Deshmukh', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Pranav Nandanwankar', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Ashutosh Joshi', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Rushikesh Deshpande', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Ajinkya Deshmukh', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Pranav Yogi', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Girish Lavekar', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_DATA_MD (MEMBER_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES ('Anand Chaudhary', 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');


--INSERT INTO SEASONS_DATA_SD

--INSERT INTO SEASONS_DATA_SD (SEASON_START_DATE, SEASON_END_DATE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (GETDATE(), NULL, GETDATE(), 'Tejas', GETDATE(), 'Tejas');


--INSERT INTO MEMBERS_EMAIL_XREF_ME

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (1, 1, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (2, 2, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (3, 3, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (4, 4, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (5, 5, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (6, 6, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (7, 7, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (8, 8, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--INSERT INTO MEMBERS_EMAIL_XREF_ME (MEMBER_ID, EMAIL_DETAILS_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (9, 9, GETDATE(), 'Tejas', GETDATE(), 'Tejas')

--UPDATE SEASONS_DATA_SD
--SET SEASON_END_DATE = GETDATE()
--WHERE SEASON_ID = 1

--INSERT INTO MEMBERS_SEASONS_WINNERS_MW
--INSERT INTO MEMBERS_SEASONS_WINNERS_MW (MEMBER_ID, SEASON_ID, LUCKY_DRAW_DATE, IS_NOTIFICATION_SENT, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (2, 1, GETDATE(), 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');

--INSERT INTO MEMBERS_SEASONS_WINNERS_MW (MEMBER_ID, SEASON_ID, LUCKY_DRAW_DATE, IS_NOTIFICATION_SENT, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
--VALUES (3, 1, GETDATE(), 'Y', GETDATE(), 'Tejas', GETDATE(), 'Tejas');