--CREATE DATABASE BRAHMVRUND

--USE BRAHMVRUND
--EMAIL_DETAILS_ED

--CREATE TABLE EMAIL_DETAILS_ED (
--	EMAIL_DETAILS_ID INT IDENTITY(1,1) PRIMARY KEY,
--	EMAIL_ID VARCHAR(50) NOT NULL,
--	CREATED_ON DATE NOT NULL,
--	CREATED_BY VARCHAR(50) NOT NULL,
--	UPDATED_ON DATE NOT NULL,
--	UPDATED_BY VARCHAR(50) NOT NULL
--);

--MEMBERS_DATA_MD

--CREATE TABLE MEMBERS_DATA_MD (
--	MEMBER_ID INT IDENTITY(1,1) PRIMARY KEY,
--	MEMBER_NAME VARCHAR(50) NOT NULL,
--	IS_ACTIVE VARCHAR(1) NOT NULL,
--	CREATED_ON DATE NOT NULL,
--	CREATED_BY VARCHAR(50) NOT NULL,
--	UPDATED_ON DATE NOT NULL,
--	UPDATED_BY VARCHAR(50) NOT NULL
--);


--SEASONS_DATA_SD

--CREATE TABLE SEASONS_DATA_SD (
--	SEASON_ID INT IDENTITY(1,1) PRIMARY KEY,
--	SEASON_START_DATE DATE NOT NULL,
--	SEASON_END_DATE DATE,
--	CREATED_ON DATE NOT NULL,
--	CREATED_BY VARCHAR(50) NOT NULL,
--	UPDATED_ON DATE NOT NULL,
--	UPDATED_BY VARCHAR(50) NOT NULL
--);


--MEMBERS_SEASONS_XREF_MS

--CREATE TABLE MEMBERS_SEASONS_XREF_MS (
--	MEMBERS_SEASONS_ID INT IDENTITY(1,1) PRIMARY KEY,
--	MEMBER_ID INT FOREIGN KEY REFERENCES MEMBERS_DATA_MD(MEMBER_ID),
--	MEMBER_FROM_SEASON_ID INT FOREIGN KEY REFERENCES SEASONS_DATA_SD(SEASON_ID),
--	MEMBER_DEACTIVATED_SEASON_ID INT FOREIGN KEY REFERENCES SEASONS_DATA_SD(SEASON_ID),
--	CREATED_ON DATE NOT NULL,
--	CREATED_BY VARCHAR(50) NOT NULL,
--	UPDATED_ON DATE NOT NULL,
--	UPDATED_BY VARCHAR(50) NOT NULL
--);

--MEMBERS_EMAIL_XREF_ME

--CREATE TABLE MEMBERS_EMAIL_XREF_ME (
--	MEMBERS_EMAIL_ID INT IDENTITY(1,1) PRIMARY KEY,
--	MEMBER_ID INT FOREIGN KEY REFERENCES MEMBERS_DATA_MD(MEMBER_ID),
--	EMAIL_DETAILS_ID INT FOREIGN KEY REFERENCES EMAIL_DETAILS_ED(EMAIL_DETAILS_ID),
--	CREATED_ON DATE NOT NULL,
--	CREATED_BY VARCHAR(50) NOT NULL,
--	UPDATED_ON DATE NOT NULL,
--	UPDATED_BY VARCHAR(50) NOT NULL
--);

--MEMBERS_SEASONS_WINNERS_MW

--CREATE TABLE MEMBERS_SEASONS_WINNERS_MW (
--	MEMBERS_SEASONS_WINNERS_ID INT IDENTITY(1,1) PRIMARY KEY,
--	MEMBER_ID INT FOREIGN KEY REFERENCES MEMBERS_DATA_MD(MEMBER_ID),
--	SEASON_ID INT FOREIGN KEY REFERENCES SEASONS_DATA_SD(SEASON_ID),
--	LUCKY_DRAW_DATE DATE NOT NULL,
--	IS_NOTIFICATION_SENT VARCHAR(1) NOT NULL,
--	CREATED_ON DATE NOT NULL,
--	CREATED_BY VARCHAR(50) NOT NULL,
--	UPDATED_ON DATE NOT NULL,
--	UPDATED_BY VARCHAR(50) NOT NULL
--);